language: go
go:
- '1.6'
branches:
  only:
  - /^v[0-9]/
before_install:
- echo "no before_install"
install:
- echo "no install"
script:
- echo "no tests"
before_deploy:
- "./cross-compile.sh"
deploy:
- provider: releases
  api_key:
    secure: "oh9i2WxMpNFCH5emF3575y+bi5eb9ZjGuHSopvy1Sj6PzhdWAPJHHHLIDvG2FZyeyd2uZnl3BrHa1fjWD/dS4XBuPCl5emf4CmyJIUBAa68q6ifGvL9GGOFwm74B0/jhZxngMSKdHbQnUpDYyP4TH+xIjM68sQpFmYBxS3INGeMxlXHIAaaF8NGRPaiMw7vFy6hr1nV8hXWGoV5E5kIOfFgWkD1R1+H6RPsCWmwqzPCAGBNcK/l6TqjnoT1hrKXZT1EpI09up8WFs4jLsDe1iwYbQ2SJxx9C6BoYniDvQEAkJE00K9bmcYiNfm4GHmZuSAb93fPInaH5vK/Jia2vldnL3BRWGahFILByDmTownfpzu7UdEVLxxIbJmzLfQ4u/CYq2fBsdxTdbG0WwsQNGeVL82WOWxaikIumgOFVkqySNw9jT7N8cU4S3psNUsqbBJtAyRi6nDFdztzlMVd0JZ0RYvA5Q+3C79mxRDtkY441fbOrl/atJ8+AQdKlSztiLWFtx2lSIbe6xFqAejvu4hnbNVTCjU9X2sjBrdYOcSBwwPQR3Lq20698dOu2qjF4S70EyMYAnd42bPLoKeElqnTFOBrMHCfLzvSCmktFS33/VG5SuSNILPr55hzw5x6qhGIKiYIWni8ateHFenytI5TmZiv0ldy0HhdASIGi7fg="
  file:
  - "tmp/meshblu-connector-installer-darwin-386"
  - "tmp/meshblu-connector-installer-darwin-amd64"
  - "tmp/meshblu-connector-installer-linux-386"
  - "tmp/meshblu-connector-installer-linux-amd64"
  - "tmp/meshblu-connector-installer-windows-386"
  - "tmp/meshblu-connector-installer-windows-amd64"
  skip_cleanup: true
  on:
    tags: true
